import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faSearch,
  faLayerGroup,
  faGraduationCap,
  faAngleDoubleRight,
  faQuestion,
  faLongArrowRight,
  faAngleDoubleLeft,
  faDuck,
  faClipboardList,
  faSoup,
  faTag,
  faHome,
  faArrowToBottom,
  faBars,
  faExternalLink,
  faQuestionCircle,
  faTimes,
  faUserChart,
  faPhone,
  faUtensilsAlt,
} from '@fortawesome/pro-light-svg-icons'

library.add(
  faSearch,
  faHome,
  faClipboardList,
  faSoup,
  faTag,
  faLayerGroup,
  faArrowToBottom,
  faGraduationCap,
  faAngleDoubleRight,
  faAngleDoubleLeft,
  faQuestion,
  faLongArrowRight,
  faDuck,
  faBars,
  faExternalLink,
  faQuestionCircle,
  faTimes,
  faUserChart,
  faPhone,
  faUtensilsAlt
)
